version: "3.6"
networks:
  local:
services:
  s3:
    container_name: s3
    image: localstack/localstack:latest
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=eu-west-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    networks:
      local:
    ports:
      - '4566'
    volumes:
      - './volumes/s3-storage/.init:/docker-entrypoint-initaws.d'
      - './volumes/s3-storage/.localstack:/tmp/localstack'

  postgresql:
    container_name: postgresql
    image: postgres:11.10
    environment:
      - POSTGRES_DB=iotd
      - POSTGRES_USER=iotd_user
      - POSTGRES_PASSWORD=iotd_pass
    networks:
        local:
    ports:
      - "5432"

  iotd:
    container_name: iotd
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgresql
      - s3
    environment:
      - DJANGO_SETTINGS_MODULE=iotd.settings
      - RDS_DB_NAME=iotd
      - RDS_USERNAME=iotd_user
      - RDS_PASSWORD=iotd_pass
      - RDS_HOSTNAME=postgresql
      - RDS_PORT=5432
      - S3_BUCKET_NAME=http://s3:4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    working_dir: /app
    entrypoint: ["/bin/sh", "-c", "python manage.py migrate && python manage.py createsu && python manage.py runserver 0.0.0.0:8000"]
    ports:
      - 8000:8000
    volumes:
      - ./iotd:/app:ro
    networks:
      local:
