name: Test code on pull request
on:
  pull_request:
    branches:
      - master
    paths:
      - "iotd/**"
      - "Dockerfile"
      - "Pipfile*"
      - ".github/workflows/pr-code-test.yaml"
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  AWS_REGION: "eu-west-1"
  AWS_GITHUB_ROLE: ${{ secrets.AWS_GITHUB_ROLE }}
  AWS_ECR_URL: ${{ secrets.AWS_ECR_URL }}
permissions:
      id-token: write
      contents: read
      pull-requests: write
jobs:
  tests:
    runs-on: ubuntu-latest
    container: python:3.7
    services:
      postgres:
        image: postgres:11.10
        env:
          POSTGRES_DB: iotd
          POSTGRES_USER: iotd_user
          POSTGRES_PASSWORD: iotd_pass
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      s3:
        image: localstack/localstack:latest
        env:
          SERVICES: s3
          DEFAULT_REGION: eu-west-1
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
        ports:
          - 4566:4566
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: pipenv install

      - name: Migrate & Run tests
        env:
          DJANGO_SETTINGS_MODULE: "iotd.settings"
          RDS_DB_NAME: "iotd"
          RDS_USERNAME: "iotd_user"
          RDS_PASSWORD: "iotd_pass"
          RDS_HOSTNAME: "postgres"
          RDS_PORT: "5432"
          S3_BUCKET_NAME: "http://s3:4566"
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
        run: |
          pipenv run python manage.py migrate
          pipenv run python manage.py createsu
          pipenv run python manage.py test
          pipenv run python manage.py runserver
