name: Plan on pull request
on:
  pull_request:
    branches:
      - master
    paths:
      - "terraform/**"
      - ".github/workflows/pr-terraform-plan.yaml"
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  AWS_REGION: "eu-west-1"
  AWS_GITHUB_ROLE: ${{ secrets.AWS_GITHUB_ROLE }}
  AWS_ECR_URL: ${{ secrets.AWS_ECR_URL }}
  ECR_REGISTRY: ${{ secrets.AWS_ECR_URL }}
  ECR_REPOSITORY: "stylesage/iotd"
  TF_WORKSPACE: "pre"
permissions:
      id-token: write
      contents: read
      pull-requests: write
jobs:
  plan-base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ env.AWS_GITHUB_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: terraform workspace
        uses: dflook/terraform-new-workspace@v1
        with:
          path: terraform/base
          workspace: ${{ env.TF_WORKSPACE }}

      - name: terraform plan
        uses: dflook/terraform-plan@v1
        with:
          path: terraform/base
          workspace: ${{ env.TF_WORKSPACE }}
  plan-app:
    runs-on: ubuntu-latest
    needs: plan-base
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ env.AWS_GITHUB_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: terraform workspace
        uses: dflook/terraform-new-workspace@v1
        with:
          path: terraform/app
          workspace: ${{ env.TF_WORKSPACE }}

      - name: terraform plan
        uses: dflook/terraform-plan@v1
        with:
          path: terraform/app
          workspace: ${{ env.TF_WORKSPACE }}
          variables: |
            image="${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:$GITHUB_SHA"
