name: Pro deployment
on:
  push:
    branches:
      - master
    paths:
      - "iotd/**"
      - "Pipfile*"
      - "terraform/**"
      - "Dockerfile"
      - ".github/workflows/pro.yaml"
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  AWS_REGION: "eu-west-1"
  TF_WORKSPACE: "pro"
  ECR_REGISTRY: ${{ secrets.AWS_ECR_URL }}
  ECR_REPOSITORY: "stylesage/iotd"
permissions:
      id-token: write
      contents: read
      pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        run: |
          docker build -t ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:$GITHUB_SHA .
          docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:$GITHUB_SHA

  apply-tf-base:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: terraform workspace
        uses: dflook/terraform-new-workspace@v1
        with:
          path: terraform/base
          workspace: ${{ env.TF_WORKSPACE }}

      - name: terraform apply
        uses: dflook/terraform-apply@v1
        with:
          path: terraform/base
          workspace: ${{ env.TF_WORKSPACE }}
          auto_approve: true

  apply-tf-app:
    runs-on: ubuntu-latest
    needs: apply-tf-base
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: terraform workspace
        uses: dflook/terraform-new-workspace@v1
        with:
          path: terraform/app
          workspace: ${{ env.TF_WORKSPACE }}

      - name: terraform apply
        uses: dflook/terraform-apply@v1
        env:
          path: terraform/app
          workspace: ${{ env.TF_WORKSPACE }}
          auto_approve: true
          variables: |
            image="${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:$GITHUB_SHA"
